### ISSUE TITLE
Logo support?

### ISSUE THREAD

**Issue by bobsutor** [vsalvino/sphinx-library#1]
Despite my setting the `html_logo` path, the library theme does not display my logo on the sidebar. Is there anything else I need to add to enable it? Thanks.

**Comment by vsalvino** [comment]
I think this was removed in Sphinx 4. Can you try with Sphinx 3.* and see if it works?
```
pip install sphinx==3.*
```

https://www.sphinx-doc.org/en/master/changes.html#release-4-0-0-released-may-09-2021

Obviously the theme will have to be updated to work with Sphinx 4 regardless...

**Comment by vsalvino** [comment]
I just tested and confirm that the logo works with Sphinx 4.1.2. Did you make sure that `html_logo` is set to the correct path to the file? Try using an absolute path and see if that works.

**Comment by jsirois** [comment]
I had a similar issue using modern Sphinx - specifying `html_logo` did not lead to any generated logo inclusion (as opposed to `html_favicon` which works fine). It looks like the deprecation death-march for the global `logo` variable in templates started here (4.0 release prep): https://github.com/sphinx-doc/sphinx/pull/8737/ and in particular note: https://github.com/sphinx-doc/sphinx/pull/8737/files#diff-a4448f37361c4e556d727657496f5bd412f17de223686b4b5c719839aff9ee47R34-R37

The fix was easy, but I don't do Sphinx version detection and just switch to `logo_url`. I'm a Sphinx newb; so I'm sure there is a more robust way to be more compatible, but PR forthcoming.
